name: Create javadoc documentation

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java-version: "21"
            java-distribution: "temurin"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}

      - name: Build with Maven
        run: |
          mvn -Dtest=\*Demo test javadoc:javadoc -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/reports/apidocs/
          force_orphan: true

  slack-notification:
    needs: [docs]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.docs.outputs.status) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v2
    with:
      job-status: ${{ needs.docs.outputs.status }}
