name: maven darwin

on: [pull_request, workflow_dispatch]

permissions:
  contents: read
  pull-requests: write

jobs:
  maven-darwin:
    runs-on: macos-13
    strategy:
      matrix:
        include:
          - java-distribution: "temurin"
            java-version: "17"
            senzingapi-version: "staging-v4"

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}

      - name: install Senzing API
        uses: senzing-factory/github-action-install-senzing-api@v3
        with:
          senzingapi-version: ${{ matrix.senzingapi-version }}

      - name: Build with Maven
        run: |
          # temp update broken file permissions
          sudo chmod 655 /opt/senzing/er/resources/templates/G2C.db
          sudo chmod 655 /opt/senzing/er/resources/templates/G2C.db.template
          mvn clean install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pjacoco -Djacoco.haltOnFailure=false -Djacoco.ignoreFailture=true -Dsenzing.support.dir="/opt/senzing/er/data"

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.0
        with:
          fail-emoji: ":red_circle:"
          min-coverage-changed-files: 80
          min-coverage-overall: 80
          pass-emoji: ":green_circle:"
          paths: ${{ github.workspace }}/target/site/**/*.xml
          skip-if-no-changes: true
          title: Code Coverage
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Overall coverage is less than 80%!')
