name: maven windows

on: [pull_request, workflow_dispatch]

permissions:
  contents: read
  pull-requests: write

jobs:
  maven-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - java-version: "17"
            java-distribution: "temurin"
            senzingsdk-version: "staging-v4"

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}

      - name: install Senzing SDK
        uses: senzing-factory/github-action-install-senzing-sdk@v3
        with:
          senzingsdk-repository-path: ${{ secrets.SENZING_WIN_BETA_REPOSITORY }}

      - name: Build with Maven
        run: |
          mvn clean install -B "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn" -Pjacoco "-Djacoco.haltOnFailure=false" "-Djacoco.ignoreFailture=true" "-Dsenzing.support.dir=C:\Program Files\Senzing\er\data"

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/target/site/**/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          title: Code Coverage
          update-comment: true
          skip-if-no-changes: true
          pass-emoji: ":green_circle:"
          fail-emoji: ":red_circle:"

      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Overall coverage is less than 80%!')
