name: spellcheck

on:
  pull_request:
    branches: [main]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: streetsidesoftware/cspell-action@v6
        with:
          config: .vscode/cspell.json
